// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzgpnwBM2HihjZPqR1EDCRa-tnyf8OA-w',
    appId: '1:712078236186:web:398616b219f3b1ec1b8fa3',
    messagingSenderId: '712078236186',
    projectId: 'woven-phoenix-447410-h8',
    authDomain: 'woven-phoenix-447410-h8.firebaseapp.com',
    databaseURL: 'https://woven-phoenix-447410-h8-default-rtdb.firebaseio.com',
    storageBucket: 'woven-phoenix-447410-h8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr8JHzl0WtNNg64MUmW6xm-YeZGnBNCps',
    appId: '1:712078236186:android:b6803a7d78781e881b8fa3',
    messagingSenderId: '712078236186',
    projectId: 'woven-phoenix-447410-h8',
    databaseURL: 'https://woven-phoenix-447410-h8-default-rtdb.firebaseio.com',
    storageBucket: 'woven-phoenix-447410-h8.firebasestorage.app',
  );
}
